trigger: none

pool: Apna Agent Pool

steps:

- task: TerraformCLI@2
  inputs:
    command: 'init'
    allowTelemetryCollection: true
- task: TerraformCLI@2
  inputs:
    command: 'fmt'
    allowTelemetryCollection: true

- task: TerraformCLI@2
  inputs:
    command: 'validate'
    allowTelemetryCollection: true


- task: TerraformCLI@2
  inputs:
    command: 'plan'
    allowTelemetryCollection: true